package com.dogfight.magic.settings_screen.widjets

import java.util.Locale


enum class VoiceCommandType(val defaultPhrase: String, val label: String) {
    FIRE("огонь", "Стрельба"),
    ONE_SHOT("выстрел", "Одиночный выстрел"),
    AFTERBURNER_ON("форсаж", "Форсаж вкл"),
    AFTERBURNER_OFF("стоп форсаж", "Форсаж выкл"),
    SPEED_PLUS("скорость плюс", "Увеличить скорость"),
    SPEED_MINUS("скорость минус", "Уменьшить скорость"),
    SPEED_MAX("максимальная скорость", "Максимальная скорость"),
    SPEED_MIN("минимальная скорость", "Минимальная скорость"),
    SPEED_HALF("половина тяги", "50% скорости"),
    ROLL_LEFT("левша", "Поворот влево"),
    ROLL_RIGHT("правша", "Поворот вправо"),
    ROLL_CENTER("прямая", "Прямо"),
    ROLL_LEFT_5("поклёвка", "Влево 5 градусов"),
    ROLL_LEFT_10("клёв", "Влево 10 градусов"),
    ROLL_RIGHT_5("поправка", "Вправо 5 градусов"),
    ROLL_RIGHT_10("правда", "Вправо 10 градусов"),
    SHIELD("щит", "Активировать щит"),
    AVADA_KEDAVRA("абракадабра", "Абракадабра"),
    BATTLE_TURN("боевой разворот", "Боевой разворот"),
    BATTLE_TURN_ENEMY("развернись", "Развернуть врага"),
    ROCKET_LAUNCH("пуск", "Пустить ракету"),
    SUPER_ROCKET_LAUNCH("супер ракета", "Пустить всенаправленную ракету"),
}

data class VoiceCommand(val defaultPhrase: String, val label: String)

val currentLocale: Locale = Locale.getDefault() // API < 24


val defaultVoiceListRu = listOf(
    VoiceCommand("огонь", "Стрельба"),
    VoiceCommand("выстрел", "Одиночный выстрел"),
    VoiceCommand("форсаж", "Форсаж вкл"),
    VoiceCommand("стоп форсаж", "Форсаж выкл"),
    VoiceCommand("скорость плюс", "Увеличить скорость"),
    VoiceCommand("скорость минус", "Уменьшить скорость"),
    VoiceCommand("максимальная скорость", "Максимальная скорость"),
    VoiceCommand("минимальная скорость", "Минимальная скорость"),
    VoiceCommand("половина тяги", "50% скорости"),
    VoiceCommand("левша", "Поворот влево"),
    VoiceCommand("правша", "Поворот вправо"),
    VoiceCommand("прямая", "Прямо"),
    VoiceCommand("поклёвка", "Влево 5 градусов"),
    VoiceCommand("клёв", "Влево 10 градусов"),
    VoiceCommand("поправка", "Вправо 5 градусов"),
    VoiceCommand("правда", "Вправо 10 градусов"),
    VoiceCommand("щит", "Активировать щит"),
    VoiceCommand("абракадабра", "Абракадабра"),
    VoiceCommand("боевой разворот", "Боевой разворот"),
    VoiceCommand("развернись", "Развернуть врага"),
    VoiceCommand("пуск", "Пустить ракету"),
    VoiceCommand("супер ракета", "Пустить всенаправленную ракету"),
)

val defaultVoiceListFr = listOf(
    VoiceCommand("feu", "Tir"),
    VoiceCommand("tir", "Tir unique"),
    VoiceCommand("postcombustion", "Activer postcombustion"),
    VoiceCommand("arrêt postcombustion", "Désactiver postcombustion"),
    VoiceCommand("vitesse plus", "Augmenter la vitesse"),
    VoiceCommand("vitesse moins", "Diminuer la vitesse"),
    VoiceCommand("vitesse maximale", "Vitesse maximale"),
    VoiceCommand("vitesse minimale", "Vitesse minimale"),
    VoiceCommand("demi poussée", "50% de la poussée"),
    VoiceCommand("gauche", "Tourner à gauche"),
    VoiceCommand("droite", "Tourner à droite"),
    VoiceCommand("tout droit", "En ligne droite"),
    VoiceCommand("cinq gauche", "Gauche 5 degrés"),
    VoiceCommand("dix gauche", "Gauche 10 degrés"),
    VoiceCommand("cinq droite", "Droite 5 degrés"),
    VoiceCommand("dix droite", "Droite 10 degrés"),
    VoiceCommand("bouclier", "Activer le bouclier"),
    VoiceCommand("abracadabra", "Abracadabra"),
    VoiceCommand("virage de combat", "Virage de combat"),
    VoiceCommand("demi-tour", "Tourner l’ennemi"),
    VoiceCommand("lancer", "Tirer une roquette"),
    VoiceCommand("super roquette", "Tirer une roquette omnidirectionnelle"),
)

val defaultVoiceListEn = listOf(
    VoiceCommand("fire", "Fire"),
    VoiceCommand("shoot", "Single shot"),
    VoiceCommand("afterburner", "Afterburner ON"),
    VoiceCommand("stop afterburner", "Afterburner OFF"),
    VoiceCommand("speed up", "Increase speed"),
    VoiceCommand("slow down", "Decrease speed"),
    VoiceCommand("maximum speed", "Maximum speed"),
    VoiceCommand("minimum speed", "Minimum speed"),
    VoiceCommand("half thrust", "50% speed"),
    VoiceCommand("left", "Turn left"),
    VoiceCommand("right", "Turn right"),
    VoiceCommand("straight", "Fly straight"),
    VoiceCommand("poke", "Turn left 5°"),
    VoiceCommand("bite", "Turn left 10°"),
    VoiceCommand("adjust", "Turn right 5°"),
    VoiceCommand("truth", "Turn right 10°"),
    VoiceCommand("shield", "Activate shield"),
    VoiceCommand("abracadabra", "Abracadabra"),
    VoiceCommand("battle turn", "Battle turn"),
    VoiceCommand("turn enemy", "Rotate enemy"),
    VoiceCommand("launch", "Rocket launch"),
    VoiceCommand("super rocket", "SuperRocket launch"),
)
val defaultVoiceListEs = listOf(
    VoiceCommand("fuego", "Disparo"),
    VoiceCommand("disparo", "Disparo único"),
    VoiceCommand("postquemador", "Activar postcombustión"),
    VoiceCommand("detener postquemador", "Desactivar postcombustión"),
    VoiceCommand("velocidad más", "Aumentar velocidad"),
    VoiceCommand("velocidad menos", "Reducir velocidad"),
    VoiceCommand("velocidad máxima", "Velocidad máxima"),
    VoiceCommand("velocidad mínima", "Velocidad mínima"),
    VoiceCommand("media potencia", "50% de empuje"),
    VoiceCommand("izquierda", "Girar a la izquierda"),
    VoiceCommand("derecha", "Girar a la derecha"),
    VoiceCommand("recto", "Todo recto"),
    VoiceCommand("cinco izquierda", "5 grados a la izquierda"),
    VoiceCommand("diez izquierda", "10 grados a la izquierda"),
    VoiceCommand("cinco derecha", "5 grados a la derecha"),
    VoiceCommand("diez derecha", "10 grados a la derecha"),
    VoiceCommand("escudo", "Activar escudo"),
    VoiceCommand("abracadabra", "Abracadabra"),
    VoiceCommand("giro de combate", "Giro de combate"),
    VoiceCommand("gírate", "Girar enemigo"),
    VoiceCommand("lanzamiento", "Lanzar misil"),
    VoiceCommand("super misil", "Lanzar misil omnidireccional"),
)
val defaultVoiceListIt = listOf(
    VoiceCommand("fuoco", "Sparo"),
    VoiceCommand("colpo", "Colpo singolo"),
    VoiceCommand("postbruciatore", "Attiva postbruciatore"),
    VoiceCommand("ferma postbruciatore", "Disattiva postbruciatore"),
    VoiceCommand("velocità più", "Aumenta velocità"),
    VoiceCommand("velocità meno", "Riduci velocità"),
    VoiceCommand("velocità massima", "Velocità massima"),
    VoiceCommand("velocità minima", "Velocità minima"),
    VoiceCommand("metà spinta", "50% spinta"),
    VoiceCommand("sinistra", "Gira a sinistra"),
    VoiceCommand("destra", "Gira a destra"),
    VoiceCommand("dritto", "Dritto"),
    VoiceCommand("cinque sinistra", "5 gradi a sinistra"),
    VoiceCommand("dieci sinistra", "10 gradi a sinistra"),
    VoiceCommand("cinque destra", "5 gradi a destra"),
    VoiceCommand("dieci destra", "10 gradi a destra"),
    VoiceCommand("scudo", "Attiva scudo"),
    VoiceCommand("abracadabra", "Abracadabra"),
    VoiceCommand("virata da combattimento", "Virata da combattimento"),
    VoiceCommand("girati", "Gira il nemico"),
    VoiceCommand("lancio", "Lancia missile"),
    VoiceCommand("super missile", "Lancia supermissile"),
)
val defaultVoiceListDe = listOf(
    VoiceCommand("feuer", "Schießen"),
    VoiceCommand("schuss", "Einzelschuss"),
    VoiceCommand("nachbrenner", "Nachbrenner ein"),
    VoiceCommand("stopp nachbrenner", "Nachbrenner aus"),
    VoiceCommand("geschwindigkeit plus", "Schneller"),
    VoiceCommand("geschwindigkeit minus", "Langsamer"),
    VoiceCommand("höchstgeschwindigkeit", "Maximale Geschwindigkeit"),
    VoiceCommand("mindestensgeschwindigkeit", "Minimale Geschwindigkeit"),
    VoiceCommand("halbe schub", "50% Schub"),
    VoiceCommand("links", "Nach links"),
    VoiceCommand("rechts", "Nach rechts"),
    VoiceCommand("geradeaus", "Geradeaus"),
    VoiceCommand("fünf links", "5 Grad links"),
    VoiceCommand("zehn links", "10 Grad links"),
    VoiceCommand("fünf rechts", "5 Grad rechts"),
    VoiceCommand("zehn rechts", "10 Grad rechts"),
    VoiceCommand("schild", "Schild aktivieren"),
    VoiceCommand("abrakadabra", "Abrakadabra"),
    VoiceCommand("kampfwendung", "Kampfwendung"),
    VoiceCommand("wenden", "Gegner wenden"),
    VoiceCommand("start", "Rakete starten"),
    VoiceCommand("super rakete", "Omni-Rakete starten"),
)
val defaultVoiceListHi = listOf(
    VoiceCommand("aag", "Goli chalao"),
    VoiceCommand("goli", "Ek goli"),
    VoiceCommand("tezi", "Tezi se chalo"),
    VoiceCommand("ruk jao", "Tezi band karo"),
    VoiceCommand("speed badhao", "Raftaar badhao"),
    VoiceCommand("speed kam", "Raftaar ghatayo"),
    VoiceCommand("full speed", "Zyada raftaar"),
    VoiceCommand("low speed", "Kam raftaar"),
    VoiceCommand("aadhi raftaar", "50 pratishat speed"),
    VoiceCommand("baayein", "Baayein ghoomo"),
    VoiceCommand("daayein", "Daayein ghoomo"),
    VoiceCommand("seedha", "Seedha chalo"),
    VoiceCommand("paanch baayein", "5 degree baayein"),
    VoiceCommand("das baayein", "10 degree baayein"),
    VoiceCommand("paanch daayein", "5 degree daayein"),
    VoiceCommand("das daayein", "10 degree daayein"),
    VoiceCommand("shield", "Shield chalu karo"),
    VoiceCommand("abrakadabra", "Abrakadabra"),
    VoiceCommand("yuddh ghoom", "Yuddh ka ghoom"),
    VoiceCommand("virodhi ghoom", "Shatru ko ghoomao"),
    VoiceCommand("missile", "Missile chhodo"),
    VoiceCommand("super", "Super missile chhodo"),
)
val defaultVoiceListPl = listOf(
    VoiceCommand("ogień", "Strzał"),
    VoiceCommand("strzał", "Pojedynczy strzał"),
    VoiceCommand("dopalacz", "Włącz dopalacz"),
    VoiceCommand("stop dopalacz", "Wyłącz dopalacz"),
    VoiceCommand("więcej prędkości", "Zwiększ prędkość"),
    VoiceCommand("mniej prędkości", "Zmniejsz prędkość"),
    VoiceCommand("maksymalna prędkość", "Maksymalna prędkość"),
    VoiceCommand("minimalna prędkość", "Minimalna prędkość"),
    VoiceCommand("połowa mocy", "50% mocy"),
    VoiceCommand("lewo", "Skręć w lewo"),
    VoiceCommand("prawo", "Skręć w prawo"),
    VoiceCommand("prosto", "Jedź prosto"),
    VoiceCommand("pięć w lewo", "5 stopni w lewo"),
    VoiceCommand("dziesięć w lewo", "10 stopni w lewo"),
    VoiceCommand("pięć w prawo", "5 stopni w prawo"),
    VoiceCommand("dziesięć w prawo", "10 stopni w prawo"),
    VoiceCommand("tarcza", "Aktywuj tarczę"),
    VoiceCommand("abrakadabra", "Abrakadabra"),
    VoiceCommand("zwrot bojowy", "Zwrot bojowy"),
    VoiceCommand("obróć wroga", "Odwróć wroga"),
    VoiceCommand("start", "Wystrzel rakietę"),
    VoiceCommand("super rakieta", "Wystrzel rakietę dookoła"),
)
val defaultVoiceListPt = listOf(
    VoiceCommand("fogo", "Disparar"),
    VoiceCommand("disparo", "Disparo único"),
    VoiceCommand("pós-combustor", "Ativar pós-combustor"),
    VoiceCommand("parar pós-combustor", "Desativar pós-combustor"),
    VoiceCommand("velocidade mais", "Aumentar velocidade"),
    VoiceCommand("velocidade menos", "Diminuir velocidade"),
    VoiceCommand("velocidade máxima", "Velocidade máxima"),
    VoiceCommand("velocidade mínima", "Velocidade mínima"),
    VoiceCommand("meia potência", "50% da potência"),
    VoiceCommand("esquerda", "Virar à esquerda"),
    VoiceCommand("direita", "Virar à direita"),
    VoiceCommand("reto", "Ir em frente"),
    VoiceCommand("cinco esquerda", "5 graus à esquerda"),
    VoiceCommand("dez esquerda", "10 graus à esquerda"),
    VoiceCommand("cinco direita", "5 graus à direita"),
    VoiceCommand("dez direita", "10 graus à direita"),
    VoiceCommand("escudo", "Ativar escudo"),
    VoiceCommand("abracadabra", "Abracadabra"),
    VoiceCommand("manobra de combate", "Virada de combate"),
    VoiceCommand("girar inimigo", "Virar inimigo"),
    VoiceCommand("lançar", "Lançar míssil"),
    VoiceCommand("super míssil", "Lançar míssil omnidirecional"),
)
val defaultVoiceListId = listOf(
    VoiceCommand("tembak", "Menembak"),
    VoiceCommand("peluru", "Tembakan tunggal"),
    VoiceCommand("pembakar tambahan", "Aktifkan pembakar tambahan"),
    VoiceCommand("hentikan pembakar", "Nonaktifkan pembakar"),
    VoiceCommand("kecepatan naik", "Tingkatkan kecepatan"),
    VoiceCommand("kecepatan turun", "Turunkan kecepatan"),
    VoiceCommand("kecepatan maksimum", "Kecepatan maksimum"),
    VoiceCommand("kecepatan minimum", "Kecepatan minimum"),
    VoiceCommand("setengah daya", "50% daya dorong"),
    VoiceCommand("kiri", "Belok kiri"),
    VoiceCommand("kanan", "Belok kanan"),
    VoiceCommand("lurus", "Lurus ke depan"),
    VoiceCommand("lima kiri", "5 derajat kiri"),
    VoiceCommand("sepuluh kiri", "10 derajat kiri"),
    VoiceCommand("lima kanan", "5 derajat kanan"),
    VoiceCommand("sepuluh kanan", "10 derajat kanan"),
    VoiceCommand("perisai", "Aktifkan perisai"),
    VoiceCommand("abrakadabra", "Abrakadabra"),
    VoiceCommand("manuver tempur", "Manuver tempur"),
    VoiceCommand("putar musuh", "Putar musuh"),
    VoiceCommand("luncurkan", "Luncurkan roket"),
    VoiceCommand("super roket", "Luncurkan roket segala arah"),
)
val defaultVoiceListTr = listOf(
    VoiceCommand("ateş", "Ateş et"),
    VoiceCommand("tek atış", "Tekli atış"),
    VoiceCommand("art yakıcı", "Art yakıcıyı aç"),
    VoiceCommand("art yakıcı dur", "Art yakıcıyı kapat"),
    VoiceCommand("hız artır", "Hızı artır"),
    VoiceCommand("hız azalt", "Hızı azalt"),
    VoiceCommand("maksimum hız", "Maksimum hız"),
    VoiceCommand("minimum hız", "Minimum hız"),
    VoiceCommand("yarım güç", "Yüzde 50 güç"),
    VoiceCommand("sol", "Sola dön"),
    VoiceCommand("sağ", "Sağa dön"),
    VoiceCommand("düz", "Düz git"),
    VoiceCommand("beş sol", "5 derece sola"),
    VoiceCommand("on sol", "10 derece sola"),
    VoiceCommand("beş sağ", "5 derece sağa"),
    VoiceCommand("on sağ", "10 derece sağa"),
    VoiceCommand("kalkan", "Kalkanı aç"),
    VoiceCommand("abrakadabra", "Abrakadabra"),
    VoiceCommand("savaş dönüşü", "Savaş dönüşü"),
    VoiceCommand("düşmanı çevir", "Düşmanı çevir"),
    VoiceCommand("fırlat", "Roket fırlat"),
    VoiceCommand("süper roket", "Her yöne roket fırlat"),
)
val defaultVoiceListVi = listOf(
    VoiceCommand("bắn", "Bắn"),
    VoiceCommand("bắn một phát", "Bắn một viên"),
    VoiceCommand("tăng tốc", "Bật tăng tốc"),
    VoiceCommand("dừng tăng tốc", "Tắt tăng tốc"),
    VoiceCommand("tăng tốc độ", "Tăng tốc độ"),
    VoiceCommand("giảm tốc độ", "Giảm tốc độ"),
    VoiceCommand("tốc độ tối đa", "Tốc độ tối đa"),
    VoiceCommand("tốc độ tối thiểu", "Tốc độ tối thiểu"),
    VoiceCommand("nửa lực đẩy", "50% lực đẩy"),
    VoiceCommand("trái", "Rẽ trái"),
    VoiceCommand("phải", "Rẽ phải"),
    VoiceCommand("thẳng", "Đi thẳng"),
    VoiceCommand("năm trái", "5 độ trái"),
    VoiceCommand("mười trái", "10 độ trái"),
    VoiceCommand("năm phải", "5 độ phải"),
    VoiceCommand("mười phải", "10 độ phải"),
    VoiceCommand("lá chắn", "Kích hoạt lá chắn"),
    VoiceCommand("abracadabra", "Abracadabra"),
    VoiceCommand("quay chiến đấu", "Quay chiến đấu"),
    VoiceCommand("xoay địch", "Xoay kẻ địch"),
    VoiceCommand("phóng", "Phóng tên lửa"),
    VoiceCommand("siêu tên lửa", "Phóng tên lửa toàn hướng"),
)
val defaultVoiceListJa = listOf(
    VoiceCommand("発射", "発射"),
    VoiceCommand("単発", "単発発射"),
    VoiceCommand("加速", "加速オン"),
    VoiceCommand("加速停止", "加速オフ"),
    VoiceCommand("速度上げて", "スピードアップ"),
    VoiceCommand("速度下げて", "スピードダウン"),
    VoiceCommand("最高速度", "最高速度"),
    VoiceCommand("最低速度", "最低速度"),
    VoiceCommand("半分速度", "50% スピード"),
    VoiceCommand("左", "左へ曲がる"),
    VoiceCommand("右", "右へ曲がる"),
    VoiceCommand("直進", "まっすぐ"),
    VoiceCommand("左5度", "左へ5度"),
    VoiceCommand("左10度", "左へ10度"),
    VoiceCommand("右5度", "右へ5度"),
    VoiceCommand("右10度", "右へ10度"),
    VoiceCommand("シールド", "シールドを起動"),
    VoiceCommand("アブラカダブラ", "アブラカダブラ"),
    VoiceCommand("戦闘ターン", "戦闘ターン"),
    VoiceCommand("敵回転", "敵を回転させる"),
    VoiceCommand("ミサイル", "ロケットを発射"),
    VoiceCommand("全方向ミサイル", "全方向ロケット発射"),
)

val defaultVoiceListKo = listOf(
    VoiceCommand("발사", "발사"),
    VoiceCommand("단발", "단발 발사"),
    VoiceCommand("가속", "가속 시작"),
    VoiceCommand("가속 정지", "가속 정지"),
    VoiceCommand("속도 증가", "속도 증가"),
    VoiceCommand("속도 감소", "속도 감소"),
    VoiceCommand("최대 속도", "최대 속도"),
    VoiceCommand("최소 속도", "최소 속도"),
    VoiceCommand("50% 추진력", "50% 추진력"),
    VoiceCommand("왼쪽", "왼쪽으로"),
    VoiceCommand("오른쪽", "오른쪽으로"),
    VoiceCommand("직진", "직진"),
    VoiceCommand("왼쪽 5도", "왼쪽 5도"),
    VoiceCommand("왼쪽 10도", "왼쪽 10도"),
    VoiceCommand("오른쪽 5도", "오른쪽 5도"),
    VoiceCommand("오른쪽 10도", "오른쪽 10도"),
    VoiceCommand("방패", "방패 활성화"),
    VoiceCommand("아브라카다브라", "아브라카다브라"),
    VoiceCommand("전투 회전", "전투 회전"),
    VoiceCommand("적 회전", "적 회전"),
    VoiceCommand("미사일 발사", "미사일 발사"),
    VoiceCommand("전방향 미사일", "전방향 미사일"),
)

val defaultVoiceListZh = listOf(
    VoiceCommand("开火", "开火"),
    VoiceCommand("单发", "单发"),
    VoiceCommand("加速", "加速启动"),
    VoiceCommand("停止加速", "加速停止"),
    VoiceCommand("加速", "加速"),
    VoiceCommand("减速", "减速"),
    VoiceCommand("最大速度", "最大速度"),
    VoiceCommand("最小速度", "最小速度"),
    VoiceCommand("一半速度", "50% 推力"),
    VoiceCommand("左转", "左转"),
    VoiceCommand("右转", "右转"),
    VoiceCommand("直走", "直走"),
    VoiceCommand("左转五度", "左转5度"),
    VoiceCommand("左转十度", "左转10度"),
    VoiceCommand("右转五度", "右转5度"),
    VoiceCommand("右转十度", "右转10度"),
    VoiceCommand("护盾", "启动护盾"),
    VoiceCommand("阿布拉卡达布拉", "阿布拉卡达布拉"),
    VoiceCommand("战斗转向", "战斗转向"),
    VoiceCommand("转动敌人", "转动敌人"),
    VoiceCommand("发射导弹", "发射导弹"),
    VoiceCommand("全向导弹", "全向导弹"),
)



val defaultVoiceList = when (currentLocale.language) {
    "ru" -> defaultVoiceListRu
    "en" -> defaultVoiceListEn
    "fr" -> defaultVoiceListFr
    "es" -> defaultVoiceListEs
    "it" -> defaultVoiceListIt
    "de" -> defaultVoiceListDe
    "hi" -> defaultVoiceListHi
    "pl" -> defaultVoiceListPl
    "pt" -> defaultVoiceListPt
    "id" -> defaultVoiceListId
    "tr" -> defaultVoiceListTr
    "vi" -> defaultVoiceListVi  // ✅ вместо "vn"
    "ja" -> defaultVoiceListJa  // ✅ вместо "vp"
    "ko" -> defaultVoiceListKo  // ✅ вместо "kr"
    "zh" -> defaultVoiceListZh  // ✅ вместо "cn"
    else -> defaultVoiceListEn
}


val defaultVoiceMap: Map<VoiceCommandType, VoiceCommand> =
    VoiceCommandType.values().zip(defaultVoiceList).toMap()